/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ServiceItem, ExtraOption, CleanerProfile, CustomerProfile, Booking, QuoteRequest, BusinessSettings } from './types';

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-domestic',
    name: 'Domestic Window Cleaning',
    description: 'Exterior glass cleaning using pure water fed pole system. Reaches up to 3 floors high safely from the ground. Includes basic wipe of frames.',
    category: 'domestic',
    basePrice: 20,
  },
  {
    id: 'srv-commercial',
    name: 'Commercial Window Cleaning',
    description: 'Professional high-grade cleaning for retail, offices, and storefronts. Scheduled according to safety regulations and business hours.',
    category: 'commercial',
    basePrice: 60,
  },
  {
    id: 'srv-conservatory',
    name: 'Conservatory Roof Cleaning',
    description: 'Full deep clean of conservatory roofs, removing algae, moss, and weather stains. Restores glass or polycarbonate panels.',
    category: 'extra',
    basePrice: 45,
  },
  {
    id: 'srv-gutters',
    name: 'Gutter Clearance & Wash',
    description: 'Clearing debris and downspouts with our powerful gutter vacuum system, followed by an exterior wash of the plastic piping.',
    category: 'extra',
    basePrice: 40,
  },
];

export const INITIAL_EXTRAS: ExtraOption[] = [
  { id: 'ext-sills', name: 'Deep Sill & Frame Cleaning', price: 10 },
  { id: 'ext-conservatory', name: 'Conservatory Glass Sides Only', price: 25 },
  { id: 'ext-fascias', name: 'Fascias & Soffits Cleaned', price: 30 },
  { id: 'ext-inside', name: 'Internal Window Cleaning (Squeegee)', price: 15 },
  { id: 'ext-solar', name: 'Solar Panels Wash (x6)', price: 20 },
];

export const INITIAL_CLEANERS: CleanerProfile[] = [
  {
    id: 'cln-1',
    name: 'Dave Carter',
    email: 'dave.carter@clearview.com',
    phone: '+44 7700 900011',
    status: 'active',
    rating: 4.9,
    completedJobsCount: 142,
  },
  {
    id: 'cln-2',
    name: 'Sarah Connor',
    email: 'sarah.c@clearview.com',
    phone: '+44 7700 900022',
    status: 'active',
    rating: 4.8,
    completedJobsCount: 98,
  },
  {
    id: 'cln-3',
    name: 'John Miller',
    email: 'john.miller@clearview.com',
    phone: '+44 7700 900033',
    status: 'active',
    rating: 4.7,
    completedJobsCount: 110,
  },
  {
    id: 'cln-4',
    name: 'Marcus Brody',
    email: 'marcus.b@clearview.com',
    phone: '+44 7700 900044',
    status: 'inactive',
    rating: 4.5,
    completedJobsCount: 35,
  },
];

export const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'cust-1',
    name: 'Tyler Troth',
    email: 'tylertroth2929@gmail.com',
    phone: '+44 7700 900155',
    addresses: ['29 High Street, Guildford, GU1 3AJ', 'Meadow Cottage, Shere, GU5 9AL'],
    propertyDetails: '3-story detached house, 14 windows, conservatory at rear.',
    notes: 'Gate code is #1404. Dog (Golden Retriever named Barney) is super friendly but keep gate locked.',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'Eleanor Vance',
    email: 'eleanor.v@outlook.com',
    phone: '+44 7700 900166',
    addresses: ['12 Oak Avenue, Woking, GU21 4EP'],
    propertyDetails: 'Semi-detached 2-story home, 8 windows, frames need deep wash.',
    notes: 'No access issues. Please text 10 mins before arrival.',
    createdAt: '2026-04-15T11:20:00Z',
  },
  {
    id: 'cust-3',
    name: 'Michael Scott',
    email: 'mscott@dundermifflin.com',
    phone: '+44 7700 900177',
    addresses: ['Paper Mill Office, Slough, SL1 4LG'],
    propertyDetails: 'Commercial office storefront, double height glass panels.',
    notes: 'Clean only outside of office hours or early mornings. Call reception upon arrival.',
    createdAt: '2026-05-01T09:15:00Z',
  },
];

export const INITIAL_SETTINGS: BusinessSettings = {
  businessName: 'ClearView Premium Cleaning',
  businessEmail: 'support@clearviewcleaning.co.uk',
  businessPhone: '+44 1483 555789',
  logoText: 'ClearView',
  workingHoursStart: '08:00',
  workingHoursEnd: '17:30',
  holidayClosures: ['2026-12-25', '2026-12-26', '2026-01-01'],
  cancellationPolicy: 'Please notify us at least 24 hours prior to your scheduled cleaning. Cancellations within 24 hours are subject to a 50% call-out fee.',
  weatherPolicy: 'We operate in light drizzle and mist using our pure-water poles. In the event of heavy downpours or high winds, we will reschedule your job and notify you via SMS/Email.',
  basePricePerWindow: 2.5,
  basePricePerFloor: 5.0,
};

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'job-101',
    customerName: 'Tyler Troth',
    customerEmail: 'tylertroth2929@gmail.com',
    customerPhone: '+44 7700 900155',
    address: '29 High Street, Guildford, GU1 3AJ',
    propertyType: 'detached',
    windowsCount: 14,
    floorsCount: 3,
    serviceId: 'srv-domestic',
    serviceName: 'Domestic Window Cleaning',
    extras: ['ext-sills', 'ext-conservatory'],
    frequency: '4-weeks',
    date: '2026-07-14', // TODAY
    timeSlot: '09:00 - 11:00',
    status: 'assigned',
    cleanerId: 'cln-1',
    cleanerName: 'Dave Carter',
    price: 75.0,
    notes: 'BARNEY (dog) is in garden. Friendly but do not leave gate open. Code #1404',
    gateCode: '#1404',
    hasDog: true,
    beforePhotos: [],
    afterPhotos: [],
    createdAt: '2026-07-10T08:30:00Z',
  },
  {
    id: 'job-102',
    customerName: 'Eleanor Vance',
    customerEmail: 'eleanor.v@outlook.com',
    customerPhone: '+44 7700 900166',
    address: '12 Oak Avenue, Woking, GU21 4EP',
    propertyType: 'semi-detached',
    windowsCount: 8,
    floorsCount: 2,
    serviceId: 'srv-domestic',
    serviceName: 'Domestic Window Cleaning',
    extras: ['ext-inside'],
    frequency: '8-weeks',
    date: '2026-07-14', // TODAY
    timeSlot: '11:30 - 13:30',
    status: 'in_progress',
    cleanerId: 'cln-2',
    cleanerName: 'Sarah Connor',
    price: 45.0,
    notes: 'Text 10 mins before arrival.',
    beforePhotos: ['https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=400&auto=format&fit=crop'],
    afterPhotos: [],
    createdAt: '2026-07-11T12:00:00Z',
  },
  {
    id: 'job-103',
    customerName: 'Michael Scott',
    customerEmail: 'mscott@dundermifflin.com',
    customerPhone: '+44 7700 900177',
    address: 'Paper Mill Office, Slough, SL1 4LG',
    propertyType: 'commercial-low',
    windowsCount: 20,
    floorsCount: 1,
    serviceId: 'srv-commercial',
    serviceName: 'Commercial Window Cleaning',
    extras: ['ext-fascias'],
    frequency: '6-weeks',
    date: '2026-07-14', // TODAY
    timeSlot: '14:30 - 16:30',
    status: 'confirmed',
    cleanerId: 'cln-1',
    cleanerName: 'Dave Carter',
    price: 110.0,
    notes: 'Call reception upon arrival. Needs full job sheet.',
    beforePhotos: [],
    afterPhotos: [],
    createdAt: '2026-07-12T14:15:00Z',
  },
  {
    id: 'job-104',
    customerName: 'Alistair Cooke',
    customerEmail: 'alistair.cooke@bbc.co.uk',
    customerPhone: '+44 7700 900188',
    address: '40 Queen Gate, Kensington, SW7 5HR',
    propertyType: 'terraced',
    windowsCount: 12,
    floorsCount: 4,
    serviceId: 'srv-domestic',
    serviceName: 'Domestic Window Cleaning',
    extras: [],
    frequency: 'one-off',
    date: '2026-07-15', // TOMORROW
    timeSlot: '10:00 - 12:00',
    status: 'assigned',
    cleanerId: 'cln-3',
    cleanerName: 'John Miller',
    price: 60.0,
    notes: 'Terraced house. Parking is restricted.',
    parkingInfo: 'Permit or pay & display',
    beforePhotos: [],
    afterPhotos: [],
    createdAt: '2026-07-12T16:00:00Z',
  },
  {
    id: 'job-105',
    customerName: 'Fiona Gallagher',
    customerEmail: 'fiona.g@chatsworth.net',
    customerPhone: '+44 7700 900199',
    address: '7 Chatsworth Estate, Manchester, M11 1ED',
    propertyType: 'terraced',
    windowsCount: 6,
    floorsCount: 2,
    serviceId: 'srv-domestic',
    serviceName: 'Domestic Window Cleaning',
    extras: ['ext-sills'],
    frequency: '4-weeks',
    date: '2026-07-12', // YESTERDAY (COMPLETED)
    timeSlot: '09:00 - 11:00',
    status: 'completed',
    cleanerId: 'cln-2',
    cleanerName: 'Sarah Connor',
    price: 35.0,
    notes: 'Simple front & back clean.',
    beforePhotos: ['https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400&auto=format&fit=crop'],
    afterPhotos: ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=400&auto=format&fit=crop'],
    cleanerNotes: 'Completed successfully. Sills wiped clean. Gate locked.',
    rating: 5,
    reviewText: 'Sarah did an absolutely amazing job! The glass is sparkling and the frames look brand new. Fully recommended.',
    reviewDate: '2026-07-12T12:30:00Z',
    invoiceId: 'INV-2026-105',
    createdAt: '2026-07-08T10:00:00Z',
  },
  {
    id: 'job-106',
    customerName: 'Tyler Troth',
    customerEmail: 'tylertroth2929@gmail.com',
    customerPhone: '+44 7700 900155',
    address: 'Meadow Cottage, Shere, GU5 9AL',
    propertyType: 'detached',
    windowsCount: 18,
    floorsCount: 2,
    serviceId: 'srv-domestic',
    serviceName: 'Domestic Window Cleaning',
    extras: ['ext-sills', 'ext-solar'],
    frequency: '8-weeks',
    date: '2026-07-10', // LAST WEEK (COMPLETED)
    timeSlot: '14:00 - 16:00',
    status: 'completed',
    cleanerId: 'cln-1',
    cleanerName: 'Dave Carter',
    price: 90.0,
    notes: 'Be careful of flower beds at the front.',
    beforePhotos: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&auto=format&fit=crop'],
    afterPhotos: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=400&auto=format&fit=crop'],
    cleanerNotes: 'Delicate care taken near flower beds. Hand squeegeed front bottom pane due to access.',
    rating: 5,
    reviewText: 'Dave is very polite, clean work, avoided the flower beds entirely. High standard!',
    reviewDate: '2026-07-10T17:00:00Z',
    invoiceId: 'INV-2026-106',
    createdAt: '2026-07-05T09:00:00Z',
  },
];

export const INITIAL_QUOTES: QuoteRequest[] = [
  {
    id: 'qte-201',
    customerName: 'Reginald Hargreeves',
    customerEmail: 'reginald@umbrellaacademy.com',
    customerPhone: '+44 7700 900301',
    address: '10 Downing St, London, SW1A 2AA',
    propertyType: 'detached',
    windowsCount: 45,
    floorsCount: 4,
    extras: ['ext-sills', 'ext-fascias', 'ext-inside'],
    frequency: '4-weeks',
    notes: 'Extremely high historic building. Need safety clearance and high-reach pure water system.',
    estimatedPrice: 225.0,
    status: 'pending',
    createdAt: '2026-07-13T10:00:00Z',
  },
  {
    id: 'qte-202',
    customerName: 'Penny Hofstadter',
    customerEmail: 'penny@gmail.com',
    customerPhone: '+44 7700 900302',
    address: 'Flat 4A, 2311 North Los Robles, Pasadena',
    propertyType: 'apartment',
    windowsCount: 4,
    floorsCount: 1,
    extras: ['ext-inside'],
    frequency: 'one-off',
    notes: 'Fourth floor apartment, windows slide inwards for internal cleaning.',
    estimatedPrice: 35.0,
    status: 'sent',
    createdAt: '2026-07-12T14:00:00Z',
  },
];
